### ISSUE TITLE
Mobile navigation does not work on Firefox

### ISSUE THREAD

**Issue by nsbtr** [colindamelio/saraswati#30]
**Describe the bug**
The menu does not expand when the menu icon is clicked. The navigation element appears to be there, but this may just be an issue with positioning.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by johnathanfong** [comment]
@nsbtr I haven't figured out the solution, but I don't think this is positioning related. The `onClick` handler is not firing in Firefox. You can tell because the `menu` button doesn't toggle icons.

**Comment by johnathanfong** [comment]
Resolved (https://github.com/colindamelio/saraswati/commit/9b1214052b5eb3a16fdc42709071c2ac0d29cdb5)
